novelai_token: []
use_token: 0
proxy:
  enable: false
  host: 127.0.0.1
  port: 7890
reverse_proxy:
  base_url: "https://image.novelai.net"
  user_url: "https://api.novelai.net"
sdapi:
  url: ""
  token: ""
translate:
  appid: ""
  appkey: ""
nsfw_check: false
api4ai:
  nsfw_threshold: 0.8
tencent:
  SecretId: ""
  SecretKey: ""
  Bucket: ""
  Region: ""
  BizType: ""
free_mode: true