novelai_token: []
use_token: 0
proxy:
  enable: false
  host: 127.0.0.1
  port: 7890
base_url: "https://api.novelai.net"
sdapi:
  url: ""
  token: ""
translate:
  appid: ""
  appkey: ""
nsfw_check: "api4ai"
api4ai:
  nsfw_threshold: 0.8
tencent:
  SecretId: ""
  SecretKey: ""
  Bucket: ""
  Region: ""
  BizType: ""
free_mode: true